name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.9"
        enable-cache: true

    - name: Set up environment
      run: |
        uv sync --dev
        uv run --with ruff ruff --version

    - name: Run ruff linting
      run: |
        uv run --with ruff ruff check . --output-format=github

    - name: Run ruff formatting check
      run: |
        uv run --with ruff ruff format --check .

    - name: Check for security issues with bandit
      run: |
        uv add --dev bandit[toml]
        uv run bandit -r clesh/ -f json -o bandit-report.json || true
        uv run bandit -r clesh/

  type-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.9"
        enable-cache: true

    - name: Set up environment
      run: |
        uv sync --dev

    - name: Run mypy type checking
      run: |
        uv add --dev mypy types-setuptools
        uv run mypy clesh/ --ignore-missing-imports || true

  dependency-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run Safety CLI to check for vulnerabilities
      uses: pyupio/safety-action@v1
      with:
        api-key: ${{ secrets.SAFETY_API_KEY }}

  docs-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.9"
        enable-cache: true

    - name: Set up environment
      run: |
        uv sync --dev

    - name: Check docstring coverage
      run: |
        uv add --dev interrogate
        uv run interrogate clesh/ --verbose --fail-under=80 || true

    - name: Validate README and examples
      run: |
        if [ -f "examples/demo.py" ]; then
          echo "Testing demo script..."
          uv run python examples/demo.py || echo "Demo script had issues"
        fi
